### ISSUE TITLE
[backend] conditions in component.yaml does not work properly

### ISSUE THREAD

**Issue by daro1337** [kubeflow/pipelines#11009]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
Kubeflow Platform (EKS)
*  KFP version: 
v2.2.0
*  KFP SDK version: 
v2.8.0

### Steps to reproduce

Conditions in the `component.yaml` file are not working correctly. It appears that the argo-workflow component takes the "IF" condition argument literally. `This is something that worked in kubeflow v1.8.0 and KFP 1.8.X (argoworkflow manifest)`

here we  I wrote dummy pipeline that prints /etc/hosts file. If `line_number=true` it should add `-n` argument to `cat` executable to print file with line numbers.

1. Compile following using KFP v2.8.0
```yaml
---
name: kfp-busybox
description: check-conditions

inputs:
- name: file
  type: String
  default: "/etc/hosts"
- name: line_number
  type: Boolean
  optional: true

implementation:
  container:
    args:
      - inputValue: file
      - if:
          cond:
            isPresent: line_number
          then:
          - -n
    image: busybox:latest
    command: [
      "/bin/cat"
    ]
```

3. compiled component:

```yaml
components:
  comp-kfp-busybox:
    executorLabel: exec-kfp-busybox
    inputDefinitions:
      parameters:
        file:
          defaultValue: /etc/hosts
          isOptional: true
          parameterType: STRING
        line_number:
          isOptional: true
          parameterType: BOOLEAN
deploymentSpec:
  executors:
    exec-kfp-busybox:
      container:
        args:
        - '{{$.inputs.parameters[''file'']}}'
        - '{"IfPresent": {"InputName": "line_number", "Then": ["-n"]}}'
        command:
        - /bin/cat
        image: busybox:latest
pipelineInfo:
  name: pipeline
root:
  dag:
    tasks:
      kfp-busybox:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-kfp-busybox
        inputs:
          parameters:
            file:
              componentInputParameter: file
            line_number:
              componentInputParameter: line_number
        taskInfo:
          name: cat-hosts
  inputDefinitions:
    parameters:
      file:
        parameterType: STRING
      line_number:
        parameterType: BOOLEAN
schemaVersion: 2.1.0
sdkVersion: kfp-2.8.0
---
platforms:
  kubernetes:
    deploymentSpec:
      executors:
        exec-kfp-busybox:
          imagePullSecret:
          - secretName: sdk-docker
```
4. upload pipeline to kubeflow platform
5. run pipeline

Output:

```
time="2024-07-16T11:16:04.035Z" level=info msg="capturing logs" argo=true
time="2024-07-16T11:16:04.153Z" level=info msg="capturing logs" argo=true
I0716 11:16:04.212214      25 launcher_v2.go:90] input ComponentSpec:{
  "inputDefinitions": {
    "parameters": {
      "file": {
        "parameterType": "STRING",
        "defaultValue": "/etc/hosts",
        "isOptional": true
      },
      "line_number": {
        "parameterType": "BOOLEAN",
        "isOptional": true
      }
    }
  },
  "executorLabel": "exec-kfp-busybox"
}
I0716 11:16:04.213720      25 cache.go:139] Cannot detect ml-pipeline in the same namespace, default to ml-pipeline.kubeflow:8887 as KFP endpoint.
I0716 11:16:04.213766      25 cache.go:116] Connecting to cache endpoint ml-pipeline.kubeflow:8887
# Kubernetes-managed hosts file.
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
fe00::0	ip6-mcastprefix
fe00::1	ip6-allnodes
fe00::2	ip6-allrouters
cat: can't open '{"IfPresent": {"InputName": "line_number", "Then": ["-n"]}}': No such file or directory
I0716 11:16:04.443096      25 launcher_v2.go:151] publish success.
F0716 11:16:04.443142      25 main.go:49] failed to execute component: exit status 1
time="2024-07-16T11:16:05.156Z" level=info msg="sub-process exited" argo=true error="<nil>"
Error: exit status 1
time="2024-07-16T11:16:06.037Z" level=info msg="sub-process exited" argo=true error="<nil>"
Error: exit status 1

```

as you can see here:

`cat: can't open '{"IfPresent": {"InputName": "line_number", "Then": ["-n"]}}': No such file or directory`

### Expected result

Print file with line numbers for instance:

```text
     1	127.0.0.1	localhost
     2	::1	localhost ip6-localhost ip6-loopback
     3	fe00::0	ip6-localnet
     4	ff00::0	ip6-mcastprefix
     5	ff02::1	ip6-allnodes
     6	ff02::2	ip6-allrouters
```

### Materials and Reference

- https://www.kubeflow.org/docs/components/pipelines/reference/component-spec/
- test example that should cover this usecase: https://github.com/kubeflow/pipelines/blob/master/backend/src/apiserver/server/test/xgboost_sample_pipeline.yaml#L304
---

Impacted by this bug? Give it a 👍.

**Comment by papagala** [comment]
This issue is critical to us since we have hundreds of pipelines that use the conditions to conditionally preprocess datasets. @juliusvonkohout FYI.

**Comment by juliusvonkohout** [comment]
@rimolive maybe something for 1.9.1

**Comment by daro1337** [comment]
@juliusvonkohout FYI It looks like center dashboard does not support `Optional` field (all are mandatory) also default value does not work in central dashboard :(

**Comment by juliusvonkohout** [comment]
> @juliusvonkohout FYI It looks like central dashboard does not support `Optional` field (all are mandatory) also `default` value does not work in central dashboard :(

@daro1337 you might want to ask @thesuperzapper about this.

**Comment by papagala** [comment]
FYI @juliusvonkohout @thesuperzapper  😄 . In other words this below fails

```python
def test_kfp_busybox(compile_pipeline):

    @dsl.pipeline()
    def _pipeline(
        file: str,
        line_number: bool,
    ):

        yamlpath="tests/_fixtures/busybox.yaml"

        # Test with 'component_text' parameter
        test = config_file_step(
            # component_text=kserve_operation_component,
            path=yamlpath,
            params={
                "file": file,
                "line_number": line_number,
            },
            name="cat-hosts",
        )

    compile_pipeline(_pipeline)
```

But this works

```python
def test_kfp_busybox(compile_pipeline):

    @dsl.pipeline()
    def _pipeline(
        file: str = default_value, # Only default values are accepted here
        line_number: bool = default_value, # Only default value accepted here
    ):
       # Any default values defined in the component below
       # are being ignored. Also optionals are flagged as required.
        yamlpath="tests/_fixtures/busybox.yaml" 

        # Test with 'component_text' parameter
        test = config_file_step(
            # component_text=kserve_operation_component,
            path=yamlpath,
            params={
                "file": file,
                "line_number": line_number,
            },
            name="cat-hosts", 
        )

    compile_pipeline(_pipeline)


```

**Comment by juliusvonkohout** [comment]
I am still busy with releasing Kubeflow 1.9.1 so for now i can only suggest to retry with the 1.9.1 RC (KFP 2.3.0) and the 2.9.0 SDK.

**Comment by papagala** [comment]
@daro1337 I guess it's a good try to retest this again. Thanks @juliusvonkohout. We will retest asap. Probably the biggest blocker we have is https://github.com/kubeflow/pipelines/issues/10050

**Comment by thesuperzapper** [comment]
I don't believe this issue is fixed?

Can someone confirm?

**Comment by daro1337** [comment]
@thesuperzapper I conducted a test today and can confirm that the issue exists in Kubeflow version `1.9.1` and KFP SDK version `2.10.1`.

**Comment by daro1337** [comment]
This is still an issue.

**Comment by papagala** [comment]
Thank you for removing the stale tag. @daro1337 looks like there's still some hope here. Thank you to all the community for working on this.

**Comment by HumairAK** [comment]
hey folks thanks for raising this issue, the issue should be fairly straight forward to resolve, there are two parts to this: 
1. Resolving inputs for command arguments
2. Handling "IF" conditions when present 

1 is easier than 2, but the fix will require changes to the driver, the logic that creates these arguments can be found [here](https://github.com/kubeflow/pipelines/blob/master/backend/src/v2/driver/driver.go#L178). The inputs information exists in the [executorInput](https://github.com/kubeflow/pipelines/blob/master/backend/src/v2/driver/driver.go#L151) and has already been resolved at this point. For (1) above, we can probably just do a conditional check, and for (2) we need to add some additional logic on parsing the "IF" json, so something like: 

```go
	var resolvedArgs []string
	for _, arg := range container.Args {
		if IsInputParameterChannel(arg) {
			resolvedArg, err := resolvePodSpecInputRuntimeParameter(arg, executorInput)
			if err != nil {
				return nil, fmt.Errorf("failed to init podSpecPatch: %w", err)
			}
			resolvedArgs = append(resolvedArgs, resolvedArg)
		} else if isConditionClause(arg){
			resolvedArg, err := resolveCondition(arg, executorInput)
			if err != nil {
				return nil, fmt.Errorf("failed to init podSpecPatch: %w", err)
			}
		}
	}
	userCmdArgs = append(userCmdArgs, resolvedArgs...)
```

`IsInputParameterChannel() `already exists in `driver/utils.go`, but `resolveCondition` and `isConditionClause` will need to be added.

**Comment by khushiiagrawal** [comment]
@hbelmiro  Hii, I believe this issue is still there and there's no activity for this. I would love to raise a PR for this issue.
Thank you.

**Comment by passionworkeer** [comment]
The least risky fix looks like handling this in the v2 driver rather than the compiler output. The emitted `{"IfPresent": ...}` payload is already present in `container.args`, so the driver can detect that JSON shape before treating it as a literal arg.

I’d split the patch into two helpers in `backend/src/v2/driver`: one that resolves normal parameter channels, and one that parses/evaluates conditional clauses against `executorInput` (including `isPresent` for optional booleans).

A good regression test would compile the busybox example from this issue and assert the launched command is `cat <file>` when absent and `cat -n <file>` when `line_number=true`.
