### ISSUE TITLE
Ability to inject item variable of ParallelFor loop into resulting task names

### ISSUE THREAD

**Issue by alexlatchford** [kubeflow/pipelines#4660]
We have a pipeline that starts with a node that lists the available region partitions (think of x50 partitions that are US states). Then it uses `ParallelFor` to train & validate x50 models. Currently the naming of those nodes in the sub-graph called for each loop item in the KFP is the same (ie. `train-model` x50). Obviously when you click on each one you can read the inputs to find the appropriate one but sometimes can take several attempts!

Digging into the code seems like [this line](https://github.com/kubeflow/pipelines/blob/master/frontend/src/lib/WorkflowParser.ts#L102) actually sets the `nodeLabel` which is rendered on the UI. It seems to read the value from the template metadata which is fine for single steps but means duplicated naming for loops. Seems like `argo` injects the argument values into the `status.nodes[].name` field which can get pretty messy depending on how complex your dependency structure is so potentially having a way to choose which inputs you can pull into the name would be best.

**Comment by Ark-kun** [comment]
Have you tried `task.set_display_name(str(loop_item))`?

**Comment by alexlatchford** [comment]
> Have you tried `task.set_display_name(str(loop_item))`?

I hadn't, just tried that out and seems like i'm getting: `RuntimeError: Internal compiler error: Found unresolved PipelineParam.`. Is that a case you expect to work? This may be something on my end as my Pipeline is pretty complex so maybe starting on a smaller example might work in my case.

**Comment by Ark-kun** [comment]
This has been fixed in master: https://github.com/kubeflow/pipelines/pull/4164

I think I need to make an out of band SDK release.

**Comment by alexlatchford** [comment]
Sweet thanks for the quick fix on this!

**Comment by Bobgy** [comment]
I just bump into this problem when implementing https://github.com/kubeflow/pipelines/pull/5337.

Even after KFP SDK supports dynamic task display name, KFP UI is not supporting it yet. After some quick investigation, I believe it's a little hard to implement, based on our current architecture.

1. KFP SDK puts dynamic task display name as an annotation on Pods
2. KFP UI loads argo workflow status to render the graph
3. KFP UI parses annotations from template to find task display name --- however, when an item is using dynamic task display name, the value on the template is not the final value. The final value does not exist in argo workflow status. We have to fetch all the Pods in the workflow to get their annotations to persist them.

We do not currently have a mechanism to load all Pods in a workflow and extract their task display names. It's not efficient enough to be added to KFP UI. Also, getting Pods from Kubernetes api is not stable, Pods will soon be GCed and it'll not be possible to see historic pipeline run results.

Therefore, I imagine a proper way to implement this feature is to add logic to persistence agent, who also persists Pod yamls when persisting an argo workflow. This is a non-trivial change.

I feel like the fastest way to allow showing dynamic task display name on KFP UI is setting task display names as KFP task output parameters, because parameters are included in argo workflow status, so we can easily parse it in KFP UI.

**Comment by Bobgy** [comment]
A more canonical way to support this is probably in KFP v2

**Comment by ChanYiLin** [comment]
> I feel like the fastest way to allow showing dynamic task display name on KFP UI is setting task display names as KFP task output parameters, because parameters are included in argo workflow status, so we can easily parse it in KFP UI.

Hi @Bobgy Is this idea workable right now ?
I have tried it by setting a lightweight function to accept the loop param and return it directly to make it become a output (weird though), however, the following step still can't accept the output as display name.

Is there any suggestion to make it workable?
Thanks!

**Comment by Bobgy** [comment]
@ChanYiLin it's not a current workaround, we need to implement logic in KFP UI to parse a specific output as display name.

**Comment by Bobgy** [comment]
Anyway, with KFP v2 compatible coming -- will be released soon, I feel that it's better getting display name from MLMD.

**Comment by rauerhans** [comment]
this is still an issue with KFP v2 btw
